sip3io/sip3-salto-ce

src/main/kotlin/io/sip3/salto/ce/Bootstrap.kt
src/main/kotlin/io/sip3/salto/ce/RoutesCE.kt
src/main/kotlin/io/sip3/salto/ce/router/Router.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprHandler.kt
src/main/resources/application.yml
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprHandlerTest.kt

Added handler for RTP Report packets from Captain.

Added RtprHandler

---

src/main/kotlin/io/sip3/salto/ce/Bootstrap.kt
src/main/resources/codecs.yml
src/test/kotlin/io/sip3/salto/ce/BootstrapTest.kt
src/test/resources/codecs.yml

- Fix reading of codec directory
- Added test

Fix reading of codec directory

---

src/main/kotlin/io/sip3/salto/ce/sdp/SdpHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipTransaction.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipTransactionTest.kt

- Fixed: NPE in SipTransaction on only TRYING 
- Fixed: NPE SdpHandler in SdpHandler on SipTransaction without request

Fix NPE in Handlers

---

src/main/kotlin/io/sip3/salto/ce/sdp/SdpHandler.kt
src/test/kotlin/io/sip3/salto/ce/util/SIPMessageUtilTest.kt

Modified: SdpHandler logging
Fixed: SIPMessageUtilTest

Fixed SdpHandler logging

---

src/main/kotlin/io/sip3/salto/ce/mongo/MongoCollectionManager.kt
src/test/kotlin/io/sip3/salto/ce/mongo/MongoCollectionManagerTest.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipCallHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipTransactionHandlerTest.kt

Modified: periodic send in tests.

Added: index creation for existing collections

---

src/main/kotlin/io/sip3/salto/ce/sip/SipRegisterHandler.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipRegisterHandlerTest.kt

Modified: handling and aggregation Registered

---

src/main/kotlin/io/sip3/salto/ce/sip/SipMessageHandler.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipMessageHandlerTest.kt

Added: Metrics calculation for invalid SIP messages

---

src/main/kotlin/io/sip3/salto/ce/rtcp/RtcpHandler.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprHandler.kt
src/main/kotlin/io/sip3/salto/ce/sdp/SdpHandler.kt
src/main/kotlin/io/sip3/salto/ce/util/MediaDescriptionFieldUtil.kt
src/main/kotlin/io/sip3/salto/ce/util/MediaUtil.kt
src/main/resources/application.yml
src/main/resources/codecs.yml
src/test/kotlin/io/sip3/salto/ce/BootstrapTest.kt
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/sdp/SdpHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/socket/ManagementSocketTest.kt
src/test/kotlin/io/sip3/salto/ce/util/MediaDescriptionFieldUtilTest.kt
src/test/kotlin/io/sip3/salto/ce/util/MediaUtilTest.kt
src/test/resources/codecs.yml

Modified: Codecs directory
Modified: MediaDescriptionField extentions

Modified: Session Id calculations

---

src/main/kotlin/io/sip3/salto/ce/rtcp/RtcpHandler.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprHandler.kt

And some refactoring for SenderReport processing

Modified: Multiple instances for RTCP and RTP-R handlers

---

src/main/kotlin/io/sip3/salto/ce/rtcp/RtcpHandler.kt

Fixed: Previous Report assignment in RtcpHandler

Added: Try-Catch for `handleSenderReport()`

---

src/main/kotlin/io/sip3/salto/ce/Bootstrap.kt
src/main/kotlin/io/sip3/salto/ce/media/MediaHandler.kt
src/main/kotlin/io/sip3/salto/ce/media/MediaManager.kt
src/main/kotlin/io/sip3/salto/ce/media/MediaSession.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprHandler.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprSession.kt
src/main/kotlin/io/sip3/salto/ce/sdp/SdpHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipTransactionHandler.kt
src/main/kotlin/io/sip3/salto/ce/socket/ManagementSocket.kt
src/main/kotlin/io/sip3/salto/ce/util/MediaAddressUtil.kt
src/test/kotlin/io/sip3/salto/ce/BootstrapTest.kt
src/test/kotlin/io/sip3/salto/ce/media/MediaHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/media/MediaManagerTest.kt
src/test/kotlin/io/sip3/salto/ce/media/MediaSessionTest.kt
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprSessionTest.kt
src/test/kotlin/io/sip3/salto/ce/sdp/SdpHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/socket/ManagementSocketTest.kt
src/test/kotlin/io/sip3/salto/ce/util/MediaAddressUtilTest.kt

Modified: Flow for SipTransaction with SDP

Added: `MediaManager` for media feature management

---

src/main/kotlin/io/sip3/salto/ce/RoutesCE.kt
src/main/kotlin/io/sip3/salto/ce/recording/RecordingHandler.kt
src/main/kotlin/io/sip3/salto/ce/router/Router.kt
src/main/resources/application.yml
src/test/kotlin/io/sip3/salto/ce/recording/RecordingHandlerTest.kt

Added: RecordingHandler

---

src/main/kotlin/io/sip3/salto/ce/recording/RecordingHandler.kt
src/test/kotlin/io/sip3/salto/ce/recording/RecordingHandlerTest.kt

Fixed: CallId assignment

---

src/main/kotlin/io/sip3/salto/ce/media/MediaHandler.kt
src/main/kotlin/io/sip3/salto/ce/media/MediaSession.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprSession.kt
src/test/kotlin/io/sip3/salto/ce/media/MediaSessionTest.kt
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprSessionTest.kt
src/test/kotlin/io/sip3/salto/ce/util/MediaDescriptionFieldUtilTest.kt

Modified: Use Double instead of Float

Added: Recording support for conditional recording

---

src/main/kotlin/io/sip3/salto/ce/sip/SipRegisterHandler.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipRegisterHandlerTest.kt

Added: Test case for `synced` flag

Added: `synced` flag for Registration SipSession

---

src/main/kotlin/io/sip3/salto/ce/attributes/AttributesRegistry.kt
src/main/kotlin/io/sip3/salto/ce/hosts/HostRegistry.kt
src/main/kotlin/io/sip3/salto/ce/media/MediaHandler.kt
src/main/kotlin/io/sip3/salto/ce/router/Router.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprHandler.kt
src/main/kotlin/io/sip3/salto/ce/sdp/SdpHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipCallHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipRegisterHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipTransactionHandler.kt
src/main/kotlin/io/sip3/salto/ce/socket/ManagementSocket.kt
src/main/resources/application.yml
src/test/kotlin/io/sip3/salto/ce/BootstrapTest.kt
src/test/kotlin/io/sip3/salto/ce/MockKSingletonExtension.kt
src/test/kotlin/io/sip3/salto/ce/attributes/AttributesRegistryTest.kt
src/test/kotlin/io/sip3/salto/ce/hosts/HostRegistryTest.kt
src/test/kotlin/io/sip3/salto/ce/router/RouterTest.kt
src/test/kotlin/io/sip3/salto/ce/sdp/SdpHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/socket/ManagementSocketTest.kt

Added: Mapping MediaAddress in SDP
Added: MockKSingletonExtension to prevent creating Singleton objects
Modified: AttributesRegistry constructor
Removed: `sdp.replace-media-address` parameter
Modified: Tests

Added: HostRepository

---

src/main/kotlin/io/sip3/salto/ce/recording/RecordingHandler.kt
src/main/resources/application.yml
src/test/kotlin/io/sip3/salto/ce/recording/RecordingHandlerTest.kt

Modified: Indexed for `rec_raw` collections
Modified: Test

Added: `src_host` and `dst_host` for rec

---

src/main/kotlin/io/sip3/salto/ce/sip/SipMessageHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipMessageParser.kt
src/main/resources/application.yml
src/test/kotlin/io/sip3/salto/ce/sip/SipMessageHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipMessageParserTest.kt

Added: SipMessageParser mode

---

src/main/kotlin/io/sip3/salto/ce/sip/SipRegisterHandler.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipRegisterHandlerTest.kt

Added: Replace caller/callee for Registrations from attributes

---

src/main/kotlin/io/sip3/salto/ce/rtpr/RtprSession.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprSessionHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipMessageHandler.kt
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprSessionHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprSessionTest.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipMessageHandlerTest.kt

Modified: Attributes from packet

Added: Attributes for RTP Report sessions

---

src/main/kotlin/io/sip3/salto/ce/rtpr/RtprHandler.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprSession.kt
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprStream.kt
src/main/resources/application.yml
src/main/resources/codecs.yml
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprHandlerTest.kt
src/test/kotlin/io/sip3/salto/ce/rtpr/RtprStreamTest.kt

Modified: GSM codec payload
Removed: `cumulativeMetrics` parameter

Added: Attributes for RTP Report Streams

---

src/main/kotlin/io/sip3/salto/ce/sip/SipRegisterHandler.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipRegisterHandlerTest.kt

Modified: Expiration logic for Active Registrations

---

pom.xml
src/main/kotlin/io/sip3/salto/ce/rtpr/RtprSessionHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipCallHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipRegisterHandler.kt
src/main/kotlin/io/sip3/salto/ce/sip/SipTransactionHandler.kt
src/main/kotlin/io/sip3/salto/ce/util/AttributeUtil.kt
src/test/kotlin/io/sip3/salto/ce/util/AttributeUtilTest.kt

Removed: Unused `vertx-js.version` property

Fixed: Save attribute value to index collection if options disabled

---

src/main/kotlin/io/sip3/salto/ce/server/Server.kt
src/main/kotlin/io/sip3/salto/ce/socket/ManagementSocket.kt
src/test/kotlin/io/sip3/salto/ce/socket/ManagementSocketTest.kt

Fixed: Handling sender address

---

src/main/kotlin/io/sip3/salto/ce/sip/SipTransaction.kt
src/test/kotlin/io/sip3/salto/ce/sip/SipCallHandlerTest.kt

Без обработки статуса 202 транзакция протухала дольше чем успел тухнуть сам звонок. Поэтому не находился звонок и не записываются атрибуты.

Added: processing all transactions during a call
